[project]
name = "emu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fsps>=0.4.7",
    "jax>=0.6.2",
    "jaxlib>=0.6.2",
    "matplotlib>=3.10.3",
    "mpi4py>=4.1.0",
    "numpy>=2.3.1",
    "ruff>=0.12.0",
    "tqdm>=4.67.1",
]
