[project]
name = "emu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.8.0",
    "matplotlib>=3.10.7",
    "mpi4py>=4.1.1",
    "numpy>=2.3.4",
    "requests>=2.32.5",
    "ripplegw>=0.0.9",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]
